version: '3.4'

services:
  truetosize:
    image: ${DOCKER_REGISTRY-}truetosize
    build:
      context: .
      dockerfile: TrueToSize/Dockerfile
  dbpostgres:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguserpassword23
      POSTGRES_DB: pgdb